#!/bin/sh
set -e

[ -f "/var/run/crond.pid" ] && rm -f "/var/run/crond.pid"
service cron start

export APACHE_RUN_DIR=/var/run/apache2
export APACHE_ARGUMENTS="-DFOREGROUND $@"

[ -f "${APACHE_RUN_DIR}/apache2.pid" ] && rm -f "${APACHE_RUN_DIR}/apache2.pid"
exec /usr/sbin/apachectl start
