#!/bin/bash

#
#   Copyright (C) MINZKN.COM
#   All rights reserved.
#
#   Maintainers
#     JaeHyuk Cho <mailto:minzkn@minzkn.com>
#

# BEGIN : EDIT FOR YOU

# exec /lib/systemd/systemd
# exec /sbin/init --log-target=journal 3>&1
# exec /sbin/init

# END   : EDIT FOR YOU

# DEFAULT

/usr/sbin/sshd -D
exec /bin/bash

# End of linuxrc
