###
#### Copyright (C) 2026 HWPORT.COM
#### All rights reserved.
#### Author: JAEHYUK CHO <mailto:minzkn@minzkn.com>
####

services:
  strongswan:
    image: hwport/ubuntu:strongswan
    container_name: strongswan
    hostname: strongswan
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    environment:
      - container=docker
      - TZ=Asia/Seoul
      - TERM=xterm
      - LC_ALL=C
      - LANG=ko_KR.UTF-8
      - EDITOR=vim
    volumes:
      - ./charon.conf:/etc/strongswan.d/charon.conf:ro
      - ./strongswan.conf:/etc/strongswan.conf:ro
      - ./ipsec.secrets:/etc/ipsec.secrets:ro
      - ./ipsec.conf:/etc/ipsec.conf:ro
#    sysctls:
#      - net.ipv4.ip_forward=1
#      - net.ipv6.conf.all.forwarding=1
    network_mode: host
    restart: unless-stopped

# End of docker-compose.yml
